hotfix: re-config TS for dfx build (required during CICD build)

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -15,6 +15,9 @@ jobs:
       - name: Checkout repository
         uses: actions/checkout@v2
 
+      - name: Install node_modules
+        run: npm install
+
       - name: Install dfx
         uses: dfinity/setup-dfx@main
 
@@ -37,6 +40,10 @@ jobs:
           printenv "DFX_DEPLOY_KEY" > "$key_pem"
           dfx identity import --disable-encryption --force smileyball "$key_pem"
           rm "$key_pem"
+          dfx identity use smileyball
+        
+      - name: Check If have permissions
+        run: dfx canister --network ic status ${{ env.SMILEYBALL_CANISTER_ID }}
 
       - name: Start DFX server in the background
         run: |
@@ -48,13 +55,40 @@ jobs:
         run: dfx canister create --all
         
       - name: Build all canisters including dependencies
-        run: dfx build
-
-      - name: Deploy Smileyball Frontend
+        run: dfx build --ic
+        
+      - name: Verify Current Directory
+        run: |
+          echo "Current working directory:"
+          pwd
+          echo "Listing all files and directories in the current location:"
+          ls -la
+      
+      - name: Check for .dfx Folder
+        run: |
+          if [ -d ".dfx" ]; then
+            echo ".dfx folder exists."
+            ls -la .dfx  # List contents of .dfx to verify structure
+          else
+            echo ".dfx folder does not exist."
+            exit 1  # Fail the workflow if .dfx does not exist
+          fi
+      
+      - name: Verify Wasm File Exists
+        run: |
+          if [ -f ".dfx/ic/canisters/smileyball_frontend/smileyball_frontend.wasm.gz" ]; then
+            echo "Wasm file exists:"
+            ls -la .dfx/ic/canisters/smileyball_frontend/
+          else
+            echo "Wasm file does not exist in .dfx/ic/canisters/smileyball_frontend/"
+            exit 1  # Fail the workflow if the Wasm file does not exist
+          fi
+    
+      - name: Deploy Smileyball Frontend on ICP
         run: |
           wallet="${{ env.WALLET_CANISTER_ID }}"
           dfx canister --network ic --wallet "$wallet" install --mode upgrade \
-            --wasm .dfx/local/canisters/smileyball_frontend/smileyball_frontend.wasm.gz \
+            --wasm .dfx/ic/canisters/smileyball_frontend/smileyball_frontend.wasm.gz \
             ${{ env.SMILEYBALL_CANISTER_ID }}
 
       - name: Stop DFX server and clean up processes
